//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class favourite_Table
    {
        public string favouriteID { get; set; }
        public string Username { get; set; }
        public string City { get; set; }
    
        public virtual City_Table City_Table { get; set; }
        public virtual User_Table User_Table { get; set; }
    }
}
