//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherReport.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Forecast_Table
    {
        public int ForecastID { get; set; }
        public string City { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int MinTemp { get; set; }
        public int MaxTemp { get; set; }
        public int Precipitation { get; set; }
        public int Humidity { get; set; }
        public int WindSpeed { get; set; }
    
        public virtual City_Table City_Table { get; set; }
    }
}
