//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherReport.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeatherReportsEntities : DbContext
    {
        public WeatherReportsEntities()
            : base("name=WeatherReportsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City_Table> City_Table { get; set; }
        public virtual DbSet<favourite_Table> favourite_Table { get; set; }
        public virtual DbSet<Forecast_Table> Forecast_Table { get; set; }
        public virtual DbSet<User_Table> User_Table { get; set; }
    }
}
